### PR TITLE
change to portfolio 

### PR DESCRIPTION
**Pull request by frnega**
i tried to do all the comments  ,about the background image i chose template 4 i could not be able to find it on figam
so am trying to change the content of the template to mine portfolio

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @frnega, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **has many pull requests** [PR#7](https://github.com/frnega/myportfolio/pull/7) please take in mind that **it is not permitted to create new pull requests** 👊🏽 We must do corrections in the correspondent PR and use the comments of code reviewers to ask questions about their comments.

- [ ] You have submitted a project, with out a descriptive Pull Request, please review the comment from last reviewer.

- [ ]  Please edit your README, following the instruction from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by franclobo — COMMENTED** [review]
Hi <STUDENT_MENTION>, 

I'm sure you are doing your best, congratulations!!! ✌🏽 
**You can contact with technical support in case you need help, kindly fill this [FORM](https://airtable.com/shrBIEhNBFdLfOSQC)**
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that:

- ❌ Don't have a professional README, please follow the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) and complete it whit the section GETTING STARTED,

image

image


- ❌ Don't have a descriptive pull request, please add a title and describe what did you do on the feature branch.

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by frnega** [comment]
Portfolio: setup and mobile first
This project has been built as part of day 3 training microverse.

Built With
HTML, CSS3, Github flow and VSCode

Authors
frehiywot Nega*

GitHub: [@githubhandle](https://github.com/frnega)
🤝 Contributing
Contributions, issues, and feature requests are welcome!

Show your support
Give a ⭐️ if you like this project!

📝 License
This project is [MIT](https://github.com/microverseinc/readme-template/blob/master/MIT.md) licensed.

**Comment by frnega** [comment]
did u see the read me it same like the template

**Review by frank1738 — CHANGES_REQUESTED** [review]
Hi @frnega , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the wrong GitHub flow. You were supposed to create a new feature branch where you were supposed to write all the changes before merging them to the master branch. In this case, it looks like your master branch contains your feature branch content. Would you please create a new repository and follow the correct githubflow  Visit this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) for more information

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request merged**
